# NumPy #

In [ ]:
# 1.  What is NumPy and what are its main advantages over regular Python lists? 

# NumPy is a Python library used for numerical computations and handling large multi-dimensional arrays.
# Performance: NumPy is faster than Python lists.
# Memory Efficiency: NumPy uses less memory because it stores data of the same type(similar data type.)
# Functionality: Provides built-in support for mathematical, statistical, and linear algebra operations.

# Coding Challenge 1:  
# Create a NumPy array from a list of numbers and perform basic arithmetic operations 
# (addition, multiplication) on the array.

import numpy as np

list1 = [1, 2, 3, 4, 5]

arr1 = np.array(list1)
print("addition : ", arr1+10)
print("multiplication : ", arr1*2)
arr1

addition :  [11 12 13 14 15]
multiplication :  [ 2  4  6  8 10]


array([1, 2, 3, 4, 5])

In [23]:
# 2.  How can you create different types of arrays in NumPy, such as arrays filled with zeros, ones, or random values? 

# There are some pre-defined functions in the lib NumPY, which canbe used to perform some operations 
# to get certain outputs such as arrays filled with zeros(np.zeros), ones(np.ones), or random values(np.random).

# Coding Challenge 2:  
# Write a Python script that creates a 3x3 array of zeros, a 3x3 array of ones, 
# and a 3x3 array of random integers between 1 and 10.

arr2 = np.zeros((3, 3))
arr2

arr3 = np.ones((3, 3))
arr3

arr4 = np.random.randint(1, 10, 9).reshape(3, 3)   #arr4 = np.random.randint(1, 10, (3, 3))
arr4

array([[2, 5, 6],
       [9, 8, 4],
       [1, 2, 8]])

In [ ]:
# 3.  Explain how array indexing and slicing work in NumPy. How does it differ from standard Python list indexing? 

# Indexing in NumPy allows access using arr[i, j] for 2D arrays. NumPy supports multi-dimensional indexing directly.
# Slicing uses arr[start:stop:step], similar to lists. Slicing returns a view, not a copy (unlike lists).

# Coding Challenge 3:  
# Create a 2D NumPy array and use slicing to extract a subarray from it. 
# For example, extract a 2x2 subarray from a 4x4 array.

arr5 = np.arange(0, 25).reshape(5, 5)
print(arr5[0:3, 3:])
arr5

[[ 3  4]
 [ 8  9]
 [13 14]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# 4.  What are some common functions in NumPy 
# for performing statistical operations, such as mean, median, and standard deviation? 

# np.min(arr10)
# np.max(arr10)
# np.sum(arr10)
# np.mean(arr10)
# np.median(arr10)
# np.std(arr10)

# Coding Challenge 4:  
# Write a Python script that computes the mean, median, and standard deviation of a NumPy array containing 100 random values.

arr6 =  np.random.randint(0, 100, 100).reshape(10, 10)

print(np.mean(arr6))
print(np.median(arr6))
print(np.std(arr6))
arr6

53.25
54.5
28.290413570677966


array([[85, 44, 28, 84, 68, 28, 25, 88, 51, 46],
       [80,  0, 71, 18, 98, 78, 16, 28, 55, 45],
       [63, 15, 50, 69, 43, 68, 79, 19, 90, 40],
       [ 0,  0, 65, 44, 55, 88, 34, 10, 64, 34],
       [96, 59, 93, 62, 89, 48,  4, 97, 26, 48],
       [42,  8, 32, 57, 46, 73, 41, 59, 46, 86],
       [73, 82, 62, 21, 22, 12, 71, 95, 33,  4],
       [54, 13, 91, 18, 88, 50, 72, 44, 65, 82],
       [75, 65, 98, 73,  8, 72, 37, 68, 50, 62],
       [ 3, 10, 32, 84, 96, 96, 96, 40, 80, 50]])

In [ ]:
# 5.  How can you perform element-wise operations and matrix operations using NumPy? Provide examples of both. 

# Element-wise operations apply to each corresponding element.
# Example: A + B adds elements of two arrays.
# Example: A * B multiplies elements of two arrays.

# Matrix operations follow linear algebra rules.
# np.dot(A, B) or A @ B performs matrix multiplication.
# A.T gives the transpose of matrix A.
# np.linalg.inv(A) computes the inverse of matrix A.

# Coding Challenge 5:  
# Create two 2D NumPy arrays and perform element-wise addition, subtraction, and matrix multiplication.

arr7 = np.arange(0, 25).reshape(5, 5)
arr7

arr8 = np.random.randint(0, 36, 25).reshape(5, 5)

print("addition :\n",arr7+arr8)
print("subtraction :\n",arr7-arr8)
print("multiplication :\n",np.dot(arr7, arr8))
print()
arr8

addition :
 [[10 36 34 33 12]
 [25 11 42 27 10]
 [14 23 35 36 39]
 [49 18 50 31 42]
 [53 33 36 26 34]]
subtraction :
 [[-10 -34 -30 -27  -4]
 [-15   1 -28 -11   8]
 [  6  -1 -11 -10 -11]
 [-19  14 -16   5  -4]
 [-13   9   8  20  14]]
multiplication :
 [[ 262   83  236  116  160]
 [ 767  413  921  556  495]
 [1272  743 1606  996  830]
 [1777 1073 2291 1436 1165]
 [2282 1403 2976 1876 1500]]



array([[10, 35, 32, 30,  8],
       [20,  5, 35, 19,  1],
       [ 4, 12, 23, 23, 25],
       [34,  2, 33, 13, 23],
       [33, 12, 14,  3, 10]])

In [ ]:
# 6.  What are broadcasting and how does it work in NumPy? 
# How can you use it to perform operations on arrays of different shapes? 

# Broadcasting is a feature that allows NumPy to perform operations on arrays of different shapes without explicit looping.

# A = np.array([[1, 2, 3], [4, 5, 6]])
# B = np.array([10, 20, 30])
# result = A + B


# Coding Challenge 6:  
# Write a Python script that demonstrates broadcasting by adding a 1D array to each row of a 2D array.

arr9 = np.arange(1, 6).reshape(5)       #([1 2 3 4 5])
arr9
arr10 = np.arange(0, 25).reshape(5, 5)

print(arr9+arr10)
arr10

[[ 1  3  5  7  9]
 [ 6  8 10 12 14]
 [11 13 15 17 19]
 [16 18 20 22 24]
 [21 23 25 27 29]]


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# 7.  How do you handle missing or NaN values in NumPy arrays? What functions or methods can be used for this purpose? 

# Use np.isnan(arr) to find NaN values.
# Remove NaNs: arr = arr[~np.isnan(arr)]
# Replace NaNs: arr[np.isnan(arr)] = value
# Replace with mean: arr[np.isnan(arr)] = np.nanmean(arr)
# Use np.nanmean(), np.nansum(), etc. to ignore NaNs in calculations.
# These functions help clean and process missing data easily.

# Coding Challenge 7:  
# Create a NumPy array with some NaN values and use NumPy functions to replace NaNs with the mean of the array.

arr11 = np.array([1, 2, np.nan, 4, np.nan, 6])           # Create array with NaN values
mean = np.nanmean(arr11)                                 # Calculate mean of non-NaN elements
arr11[np.isnan(arr11)] = mean                            # Replace NaNs with the mean

print("Array after replacing NaNs with mean:\n", arr11)


Array after replacing NaNs with mean:
 [1.   2.   3.25 4.   3.25 6.  ]


In [ ]:
# 8.  Explain the purpose and usage of NumPy's `reshape()` and `flatten()` methods. 
# How can you change the shape of an array? 

# reshape(): Changes the shape of an array without changing its data.
# flatten(): Converts a multi-dimensional array into a 1D array.

# Coding Challenge 8:  
# Write a Python script that creates a 1D array with 12 elements, reshapes it into a 3x4 array, 
# and then flattens it back into a 1D array.

arr12 = np.arange(0, 12)
arr13 = arr12.reshape(3, 4)
print(arr13)
print(arr13.flatten())

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [ ]:
# 9.  What is the role of `numpy.linalg` for linear algebra operations? 
# How can you use it to perform operations like matrix inversion or eigenvalue computation? 

# Role of numpy.linalg:
# numpy.linalg is a submodule for linear algebra operations.
# It provides functions for solving equations, inversion, and more.

# Common Operations:

# Matrix Inversion
# np.linalg.inv(A)

# Solving Linear Equations (Ax = b)
# np.linalg.solve(A, b)

# Determinant
# np.linalg.det(A)

# Eigenvalues and Eigenvectors
# values, vectors = np.linalg.eig(A)

# Matrix Rank
# np.linalg.matrix_rank(A)


# Coding Challenge 9:  
# Create a 2x2 matrix and use `numpy.linalg.inv()` to compute its inverse. 
# Also, compute the eigenvalues and eigenvectors of the matrix.

import numpy as np

arr14 = np.arange(1, 5).reshape(2, 2)

inverse = np.linalg.inv(arr14)
print("inverse :\n",inverse)
values, vectors = np.linalg.eig(arr14)
print("eigenvalues and eigenvectors of the matrix :\n", values, vectors)

inverse :
 [[-2.   1. ]
 [ 1.5 -0.5]]
eigenvalues and eigenvectors of the matrix :
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# 10.  How can you save and load NumPy arrays to and from files? What formats are supported?

# Saving NumPy Arrays:
# Save as .npy (binary format)
# np.save('array.npy', arr)

# Save multiple arrays in .npz (compressed)
# np.savez('arrays.npz', a=arr1, b=arr2)

# Save as text file (e.g., CSV or TXT)
# np.savetxt('array.txt', arr, delimiter=',')

# Loading NumPy Arrays:
# Load .npy file
# arr = np.load('array.npy')

# Load .npz file
# data = np.load('arrays.npz')
# arr1 = data['a']

# Load text file
# arr = np.loadtxt('array.txt', delimiter=',')

# Supported Formats:

# .npy (efficient binary format)
# .npz (compressed archive of .npy files)
# .txt, .csv (text-based)

# Coding Challenge 10:  
# Write a Python script that saves a NumPy array to a file using `numpy.save()` and then loads it back using `numpy.load()`.

import numpy as np

arr15 = np.arange(0, 6)
arr15.resize(2, 3)  # Resize in-place

np.save('my_array.npy', arr15)           # Save the array
loaded_arr = np.load('my_array.npy')     # Load the array
print("Loaded array:\n", loaded_arr)     # Print the loaded array

Loaded array:
 [[0 1 2]
 [3 4 5]]
